# mcp-pvsneslib SNES Project
# Generated by MCP-PVSnesLib configure_tools

# Check for PVSnesLib installation
ifeq ($(strip $(PVSNESLIB_HOME)),)
$(error "Please create an environment variable PVSNESLIB_HOME by following this guide: https://github.com/alekmaul/pvsneslib/wiki/Installation")
endif

include ${PVSNESLIB_HOME}/devkitsnes/snes_rules

.PHONY: all clean

#---------------------------------------------------------------------------------
# ROMNAME is used in snes_rules file
export ROMNAME := mcppvsneslib

# Additional compiler flags
export PVSNESLIB_DEBUG := 1

all: $(ROMNAME).sfc

clean: cleanBuildRes cleanRom cleanGfx

# Add your custom targets here
# Example:
# graphics: sprite.pic background.pic
# \t@echo "Graphics converted"

# sprite.pic: graphics/sprite.png
# \t$(GFXCONV) -s 8 -o 16 -u 16 -p -e 0 -i $<
